# Generated by Django 5.0.1 on 2024-12-29 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="巡检ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="巡检标题", max_length=100)),
                ("location", models.CharField(help_text="巡检地点", max_length=255)),
                (
                    "latitude",
                    models.FloatField(blank=True, help_text="纬度", null=True),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, help_text="经度", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        help_text="巡检状态",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, help_text="开始时间", null=True),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, help_text="结束时间", null=True),
                ),
                ("summary", models.TextField(blank=True, help_text="巡检总结")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        help_text="巡检人员",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检记录",
                "verbose_name_plural": "巡检记录",
                "db_table": "inspection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="事件ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="问题描述")),
                (
                    "manual_description",
                    models.TextField(blank=True, help_text="手工输入的描述"),
                ),
                ("ai_analysis", models.TextField(blank=True, help_text="AI分析结果")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        help_text="所属巡检",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inspections.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件点",
                "verbose_name_plural": "事件点",
                "db_table": "event",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="文件ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("voice", "语音"), ("photo", "照片")],
                        help_text="文件类型",
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(help_text="文件URL")),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="语音时长(秒)", null=True
                    ),
                ),
                ("text", models.TextField(blank=True, help_text="语音识别文本")),
                (
                    "local_path",
                    models.CharField(
                        blank=True, help_text="本地文件路径", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="所属事件",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="inspections.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "媒体文件",
                "verbose_name_plural": "媒体文件",
                "db_table": "media_file",
                "ordering": ["created_at"],
            },
        ),
    ]
